'use client';

import { useState } from 'react';

const initialRates = { roofTile: 6.5, roofMetal: 5.5, driveway: 4.2, paths: 4.2, minCharge: 250, storey: 15, steep: 20, heavy: 25, access: 150, solar: 180, gutters: 220, gst: 10, validity: 30 };
const initialQuotes = [
  { number: 'Q-2026-0147', customer: 'Daniel Okafor', address: '12 Banksia Cres, Glenmore Park NSW', services: 'Roof · Driveway', total: 1842, status: 'Sent' },
  { number: 'Q-2026-0146', customer: 'Priya Raman', address: '48 Wattle St, Castle Hill NSW', services: 'Roof · Solar', total: 2310, status: 'Accepted' },
  { number: 'Q-2026-0145', customer: 'Tom & Ellie Brandt', address: '7 Coral Tree Dr, Kellyville NSW', services: 'Driveway · Paths', total: 640, status: 'Draft' },
  { number: 'Q-2026-0144', customer: 'Margaret Lau', address: '133 Old Northern Rd, Baulkham Hills NSW', services: 'Roof · Gutters', total: 1975, status: 'Rejected' },
  { number: 'Q-2026-0139', customer: 'Sam Nguyen', address: '5/21 Windsor Rd, Northmead NSW', services: 'House wash', total: 890, status: 'Expired' },
];
const suggestions = ['22 Jacaranda Ave, Baulkham Hills NSW 2153', '22 Jacaranda Pl, Kellyville NSW 2155', '22A Jacaranda Rd, Cherrybrook NSW 2126'];
const flow = ['customer', 'measure', 'assess', 'price', 'send'];
const money = (value) => `$${Number(value).toLocaleString('en-AU', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const today = new Date(2026, 8, 4);

function Button({ children, className = '', ...props }) { return <button className={`button ${className}`} {...props}>{children}</button>; }
function Field({ label, children }) { return <label className="field"><span>{label}</span>{children}</label>; }

export default function Home() {
  const [screen, setScreen] = useState('quotes');
  const [filter, setFilter] = useState('All');
  const [quotes, setQuotes] = useState(initialQuotes);
  const [rates, setRates] = useState(initialRates);
  const [customer, setCustomer] = useState({ name: '', mobile: '', email: '', address: '', located: false });
  const [areas, setAreas] = useState({ roof: 186, driveway: 62, paths: 0 });
  const [assess, setAssess] = useState({ material: 'Tile', pitch: 22.5, storeys: 1, condition: 'Moderate', access: 'Easy', solar: false, gutters: false });
  const [notes, setNotes] = useState('');
  const [override, setOverride] = useState('');
  const [channel, setChannel] = useState('email');
  const [sent, setSent] = useState(false);

  const setCustomerValue = (key, value, located = false) => setCustomer((current) => ({ ...current, [key]: value, ...(key === 'address' ? { located } : {}) }));
  const setRate = (key, value) => setRates((current) => ({ ...current, [key]: Number(value) || 0 }));
  const setArea = (key, value) => setAreas((current) => ({ ...current, [key]: Number(value) || 0 }));
  const setAssessment = (key, value) => setAssess((current) => ({ ...current, [key]: value }));
  const calc = () => {
    const items = [], adjustments = [], factor = 1 / Math.cos(assess.pitch * Math.PI / 180);
    const roofRate = assess.material === 'Tile' ? rates.roofTile : rates.roofMetal;
    if (areas.roof > 0) items.push({ label: `Roof wash · ${assess.material}`, detail: `${areas.roof} m² footprint × ${factor.toFixed(2)} pitch = ${(areas.roof * factor).toFixed(0)} m² @ $${roofRate}/m²`, amount: areas.roof * factor * roofRate });
    if (areas.driveway > 0) items.push({ label: 'Driveway clean', detail: `${areas.driveway} m² @ $${rates.driveway}/m²`, amount: areas.driveway * rates.driveway });
    if (areas.paths > 0) items.push({ label: 'Paths & patio', detail: `${areas.paths} m² @ $${rates.paths}/m²`, amount: areas.paths * rates.paths });
    const roofAmount = items[0]?.amount || 0;
    if (assess.storeys === 2) adjustments.push({ label: `Two-storey surcharge +${rates.storey}%`, amount: roofAmount * rates.storey / 100 });
    if (assess.pitch >= 30) adjustments.push({ label: `Steep roof surcharge +${rates.steep}%`, amount: roofAmount * rates.steep / 100 });
    if (assess.condition === 'Heavy') adjustments.push({ label: `Heavy moss / lichen +${rates.heavy}%`, amount: roofAmount * rates.heavy / 100 });
    if (assess.access === 'Difficult') adjustments.push({ label: 'Difficult access', amount: rates.access });
    if (assess.solar) items.push({ label: 'Solar panel clean', detail: 'Fixed price', amount: rates.solar });
    if (assess.gutters) items.push({ label: 'Gutter clean', detail: 'Fixed price', amount: rates.gutters });
    let subtotal = items.reduce((sum, item) => sum + item.amount, 0) + adjustments.reduce((sum, item) => sum + item.amount, 0);
    if (subtotal < rates.minCharge && subtotal > 0) { adjustments.push({ label: 'Minimum call-out applied', amount: rates.minCharge - subtotal }); subtotal = rates.minCharge; }
    if (override !== '' && !Number.isNaN(Number(override))) subtotal = Number(override);
    const gst = subtotal * rates.gst / 100;
    return { items, adjustments, subtotal, gst, total: subtotal + gst };
  };
  const quote = calc();
  const resetNew = () => { setCustomer({ name: '', mobile: '', email: '', address: '', located: false }); setSent(false); setOverride(''); setScreen('customer'); };
  const next = () => { if (screen === 'send') { if (sent) { setQuotes([{ number: 'Q-2026-0148', customer: customer.name, address: customer.address, services: 'Roof · Driveway', total: quote.total, status: 'Sent' }, ...quotes]); setSent(false); setScreen('quotes'); } else setSent(true); } else setScreen(flow[flow.indexOf(screen) + 1]); };
  const back = () => { if (screen === 'customer') setScreen('quotes'); else if (sent) setSent(false); else setScreen(flow[flow.indexOf(screen) - 1]); };

  if (screen === 'quotes') return <Quotes quotes={quotes} filter={filter} setFilter={setFilter} onNew={resetNew} onSettings={() => setScreen('settings')} />;
  if (screen === 'settings') return <Settings rates={rates} setRate={setRate} onQuotes={() => setScreen('quotes')} />;
  return <main className="shell"><header className="flow-header"><Button onClick={back} className="back">‹ Back</Button><span>Step {flow.indexOf(screen) + 1} of 5</span><Button onClick={() => setScreen('quotes')} className="save">Save draft</Button><div className="progress">{flow.map((step, index) => <i className={index <= flow.indexOf(screen) ? 'active' : ''} key={step} />)}</div></header>{screen === 'customer' && <Customer customer={customer} setCustomerValue={setCustomerValue} />}{screen === 'measure' && <Measure areas={areas} setArea={setArea} />}{screen === 'assess' && <Assess assess={assess} setAssessment={setAssessment} notes={notes} setNotes={setNotes} rates={rates} />}{screen === 'price' && <Price quote={quote} rates={rates} override={override} setOverride={setOverride} />}{screen === 'send' && <Send customer={customer} quote={quote} channel={channel} setChannel={setChannel} sent={sent} />}{!sent && <footer className="flow-footer">{(screen === 'measure' || screen === 'assess') && <div className="running"><span>Running estimate inc. GST</span><strong>{money(quote.total)}</strong></div>}<Button className={`next ${screen === 'customer' && !(customer.name && customer.located) ? 'disabled' : ''}`} disabled={screen === 'customer' && !(customer.name && customer.located)} onClick={next}>{screen === 'customer' ? 'Locate & measure' : screen === 'measure' ? 'Assess property' : screen === 'assess' ? 'Calculate price' : screen === 'price' ? 'Review & send' : channel === 'email' ? 'Send by email' : 'Send SMS link'}</Button></footer>}{sent && <footer className="flow-footer"><Button className="next" onClick={next}>Back to quotes</Button></footer>}</main>;
}

function Quotes({ quotes, filter, setFilter, onNew, onSettings }) { const visible = quotes.filter((quote) => filter === 'All' || quote.status === filter); return <main className="shell"><section className="page"><div className="topbar"><div><p>Rinse & Restore Exterior Cleaning</p><h1>Quotes</h1></div><Button className="accent" onClick={onNew}>＋ New quote</Button></div><div className="stats"><Stat label="Sent this month" value={quotes.filter((quote) => quote.status !== 'Draft').length} /><Stat label="Accepted" value={quotes.filter((quote) => quote.status === 'Accepted').length} accent /><Stat label="Pipeline" value={money(quotes.filter((quote) => quote.status === 'Sent').reduce((sum, quote) => sum + quote.total, 0)).replace('.00', '')} /></div><div className="filters">{['All', 'Draft', 'Sent', 'Accepted'].map((name) => <Button key={name} className={filter === name ? 'selected' : ''} onClick={() => setFilter(name)}>{name}</Button>)}</div><div className="quote-grid">{visible.map((quote) => <article className="quote-card" key={quote.number}><div className="quote-head"><div><strong>{quote.customer}</strong><span>{quote.address}</span></div><em className={`status ${quote.status.toLowerCase()}`}>{quote.status}</em></div><div className="quote-meta"><span>{quote.number} · {quote.services}</span><strong>{money(quote.total)}</strong></div></article>)}</div></section><Nav onSettings={onSettings} /></main>; }
function Stat({ label, value, accent }) { return <div className="stat"><span>{label}</span><strong className={accent ? 'green' : ''}>{value}</strong></div>; }
function Nav({ onSettings, onQuotes, active = 'quotes' }) { return <nav className="bottom-nav"><Button className={active === 'quotes' ? 'active' : ''} onClick={onQuotes}>Quotes</Button><Button className={active === 'settings' ? 'active' : ''} onClick={onSettings}>Pricing</Button></nav>; }
function Customer({ customer, setCustomerValue }) { return <section className="page form-page"><h1>Who is this quote for?</h1><Field label="Customer name"><input value={customer.name} onChange={(event) => setCustomerValue('name', event.target.value)} placeholder="e.g. Sarah Mitchell" /></Field><Field label="Mobile"><input type="tel" value={customer.mobile} onChange={(event) => setCustomerValue('mobile', event.target.value)} placeholder="04xx xxx xxx" /></Field><Field label="Email"><input type="email" value={customer.email} onChange={(event) => setCustomerValue('email', event.target.value)} placeholder="name@example.com" /></Field><Field label="Property address"><input value={customer.address} onChange={(event) => setCustomerValue('address', event.target.value)} placeholder="Start typing an Australian address" />{customer.address.length > 1 && !customer.located && <div className="suggestions">{suggestions.map((item) => <button key={item} onClick={() => setCustomerValue('address', item, true)}>{item}</button>)}</div>}{customer.located && <small className="located">● Property located · -33.7581, 150.9912</small>}</Field></section>; }
function Measure({ areas, setArea }) { return <section className="page"><h1>Outline the surfaces</h1><p className="muted">22 Jacaranda Ave, Baulkham Hills NSW 2153</p><div className="map"><div className="aerial">aerial imagery</div><div className="polygon roof" /><div className="polygon driveway" /><div className="map-actions"><Button onClick={() => setArea('roof', areas.roof + 5)}>＋ Add point</Button><Button onClick={() => setArea('roof', Math.max(0, areas.roof - 5))}>Undo</Button></div></div><div className="area-list">{[['roof', 'Roof footprint', '1 polygon · horizontal'], ['driveway', 'Driveway', '1 polygon'], ['paths', 'Paths & patio', 'Optional']].map(([key, label, note]) => <div className="area-row" key={key}><div><strong>{label}</strong><span>{note}</span></div><label><input type="number" value={areas[key]} onChange={(event) => setArea(key, event.target.value)} /> m²</label></div>)}</div><p className="muted hint">Areas are horizontal footprints. Roof pitch is applied in the next step.</p></section>; }
function OptionGroup({ title, value, options, onChange }) { return <div className="option-group"><div className="group-label"><strong>{title}</strong></div><div className="options">{options.map(([option, sub]) => <Button key={option} className={value === option ? 'chosen' : ''} onClick={() => onChange(option)}><strong>{option}</strong><small>{sub}</small></Button>)}</div></div>; }
function Assess({ assess, setAssessment, notes, setNotes, rates }) { return <section className="page form-page"><h1>Property conditions</h1><OptionGroup title="Roof material" value={assess.material} onChange={(value) => setAssessment('material', value)} options={[['Tile', `$${rates.roofTile}/m²`], ['Metal / Colorbond', `$${rates.roofMetal}/m²`]]} /><OptionGroup title="Roof pitch" value={assess.pitch} onChange={(value) => setAssessment('pitch', value)} options={[[15, '~15°'], [22.5, '~22.5°'], [30, '30°+']]} /><OptionGroup title="Storeys" value={assess.storeys} onChange={(value) => setAssessment('storeys', value)} options={[[1, ''], [2, `+${rates.storey}%`]]} /><OptionGroup title="Roof condition" value={assess.condition} onChange={(value) => setAssessment('condition', value)} options={[[ 'Light', 'Dust, dirt'], ['Moderate', 'Some moss'], ['Heavy', `Moss +${rates.heavy}%`]]} /><OptionGroup title="Access" value={assess.access} onChange={(value) => setAssessment('access', value)} options={[[ 'Easy', 'Clear, level'], ['Difficult', `+$${rates.access}`]]} /><div className="extras"><strong>Extras</strong>{[['solar', 'Solar panel clean', rates.solar], ['gutters', 'Gutter clean', rates.gutters]].map(([key, label, price]) => <Button key={key} className={assess[key] ? 'chosen extra' : 'extra'} onClick={() => setAssessment(key, !assess[key])}><span>{assess[key] ? '✓' : '□'} {label}</span><strong>{money(price)}</strong></Button>)}</div><Field label="Estimator notes"><input value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Trees over rear roof, gate access on left" /></Field></section>; }
function Price({ quote, rates, override, setOverride }) { return <section className="page form-page"><h1>Quote Q-2026-0148</h1><div className="total-card"><span>Total inc. GST</span><strong>{money(quote.total)}</strong><small>Valid {rates.validity} days</small></div><div className="line-card">{[...quote.items, ...quote.adjustments].map((item) => <div className="line" key={item.label}><div><strong>{item.label}</strong><span>{item.detail || ''}</span></div><strong>{money(item.amount)}</strong></div>)}<div className="line summary"><span>Subtotal</span><strong>{money(quote.subtotal)}</strong></div><div className="line summary"><span>GST {rates.gst}%</span><strong>{money(quote.gst)}</strong></div></div><Field label="Manual override"><input type="number" value={override} onChange={(event) => setOverride(event.target.value)} placeholder="Calculated subtotal" /></Field><p className="muted legal">Measurements and pricing are estimated using aerial imagery and information available at the time of quotation.</p></section>; }
function Send({ customer, quote, channel, setChannel, sent }) { if (sent) return <section className="page sent"><div className="check">✓</div><h1>Quote sent</h1><p>{'Q-2026-0148'} for {money(quote.total)} was sent to {channel === 'email' ? customer.email || 'the customer' : customer.mobile || 'the customer'}.<br />Status is now <strong>Sent</strong>.</p></section>; return <section className="page form-page"><h1>Send to {(customer.name || 'customer').split(' ')[0]}</h1><div className="channel-grid">{[['email', 'Email', customer.email || 'No email entered'], ['sms', 'SMS link', customer.mobile || 'No mobile entered']].map(([key, label, target]) => <Button key={key} className={channel === key ? 'chosen' : ''} onClick={() => setChannel(key)}><strong>{label}</strong><span>{target}</span></Button>)}</div><div className="preview"><div className="preview-top"><strong>Rinse & Restore</strong><span>Q-2026-0148<br />4 Sep 2026</span></div><hr /><strong>{customer.name}</strong><span>{customer.address}</span>{quote.items.map((item) => <div className="preview-line" key={item.label}><span>{item.label}</span><strong>{money(item.amount)}</strong></div>)}<hr /><div className="preview-line"><span>Total inc. GST</span><strong>{money(quote.total)}</strong></div></div></section>; }
function Settings({ rates, setRate, onQuotes }) { return <main className="shell"><section className="page form-page settings"><p className="muted">Applied to every new quote</p><h1>Pricing rules</h1>{[['Rates per m²', [['roofTile', 'Roof · tile', '$', '/m²'], ['roofMetal', 'Roof · metal / Colorbond', '$', '/m²'], ['driveway', 'Driveway', '$', '/m²'], ['paths', 'Paths & patio', '$', '/m²']]], ['Surcharges', [['storey', 'Two storey', '+', '%'], ['steep', 'Steep roof (30°+)', '+', '%'], ['heavy', 'Heavy moss / lichen', '+', '%'], ['access', 'Difficult access', '$', '']]], ['Fixed extras & rules', [['solar', 'Solar panel clean', '$', ''], ['gutters', 'Gutter clean', '$', ''], ['minCharge', 'Minimum call-out', '$', ''], ['gst', 'GST', '', '%'], ['validity', 'Quote validity', '', 'days']]]].map(([title, rows]) => <div className="rate-group" key={title}><label>{title}</label><div className="line-card">{rows.map(([key, label, prefix, suffix]) => <div className="rate-row" key={key}><span>{label}</span><div>{prefix}<input type="number" value={rates[key]} onChange={(event) => setRate(key, event.target.value)} />{suffix}</div></div>)}</div></div>)}<p className="muted">Changes apply to new quotes immediately. Sent quotes keep the rates they were priced with.</p></section><Nav active="settings" onSettings={() => {}} onQuotes={onQuotes} /></main>; }
